apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: order-service
  annotations:
    backstage.io/techdocs-ref: value
  description: This service receives new orders and processes them
  tags:
    - nodejs
    - backend
spec:
  type: service
  lifecycle: production
  owner: backend-team
